import java.util.ArrayList;
import java.util.List;

public class Output {



    public static void main(String[] args) {

       Input input = new Input();
       ArrayList<PeriodTime> periodTimeFromInput = input.getPeriodTimes();
       ArrayList<Room> roomsFromInput = input.getRooms();
       ArrayList<Teacher> teachersFromInput = input.getTeachers();
       ArrayList<Subject> subjectsFromInput = input.getSubjects();
       ArrayList<StudentGroup> groupsFromInput = input.getGroups();

        CSP cspAlgorithm = new CSP(periodTimeFromInput,roomsFromInput,teachersFromInput,subjectsFromInput, groupsFromInput);
        TimeTable res =  cspAlgorithm.running();

        List<Slot> slots = res.getReadySlots();

        System.out.println(input.getPeriodTimes().size());

        for(int i = 0; i < input.getGroups().size(); i++){
            StudentGroup currGroup = input.getGroups().get(i);
            System.out.println("GROUP: "+currGroup.getName());
            System.out.println("Day     |     10:00 - 11:00     |     11:00 - 12:00     |     12:00 - 13:00     |     13:00 - 14:00     |     14:00 - 15:00     |     15:00 - 16:00     |");
            System.out.println("--------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+");
            System.out.println("MN      | " + (getSlot(slots,input.getPeriodTimes().get(0),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(0),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(0),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | " + (getSlot(slots,input.getPeriodTimes().get(1),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(1),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(1),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | "+ (getSlot(slots,input.getPeriodTimes().get(2),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(2),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(2),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | "+ (getSlot(slots,input.getPeriodTimes().get(3),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(3),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(3),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | "+ (getSlot(slots,input.getPeriodTimes().get(4),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(4),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(4),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | "+ (getSlot(slots,input.getPeriodTimes().get(5),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(5),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(5),currGroup).getSubject().getType()) : String.format("%1$21s","----------------"))+ " |");
            System.out.println("        | " + (getSlot(slots,input.getPeriodTimes().get(0),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(0),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(0),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | " + (getSlot(slots,input.getPeriodTimes().get(1),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(1),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(1),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | "+ (getSlot(slots,input.getPeriodTimes().get(2),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(2),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(2),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | "+ (getSlot(slots,input.getPeriodTimes().get(3),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(3),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(3),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | "+ (getSlot(slots,input.getPeriodTimes().get(4),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(4),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(4),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | "+ (getSlot(slots,input.getPeriodTimes().get(5),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(5),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(5),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------"))+ " |");
            System.out.println("--------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+");
            System.out.println("TU      | " + (getSlot(slots,input.getPeriodTimes().get(6),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(6),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(6),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | " + (getSlot(slots,input.getPeriodTimes().get(7),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(7),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(7),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | "+ (getSlot(slots,input.getPeriodTimes().get(8),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(8),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(8),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | "+ (getSlot(slots,input.getPeriodTimes().get(9),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(9),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(9),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | "+ (getSlot(slots,input.getPeriodTimes().get(10),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(10),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(10),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | "+ (getSlot(slots,input.getPeriodTimes().get(11),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(11),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(11),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) + " |");
            System.out.println("        | " + (getSlot(slots,input.getPeriodTimes().get(6),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(6),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(6),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | " + (getSlot(slots,input.getPeriodTimes().get(7),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(7),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(7),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | "+ (getSlot(slots,input.getPeriodTimes().get(8),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(8),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(8),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | "+ (getSlot(slots,input.getPeriodTimes().get(9),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(9),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(9),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | "+ (getSlot(slots,input.getPeriodTimes().get(10),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(10),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(10),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | "+ (getSlot(slots,input.getPeriodTimes().get(11),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(11),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(11),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------"))+ " |");
            System.out.println("--------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+");
            System.out.println("WD      | " + (getSlot(slots,input.getPeriodTimes().get(12),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(12),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(12),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | " + (getSlot(slots,input.getPeriodTimes().get(13),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(13),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(13),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | "+ (getSlot(slots,input.getPeriodTimes().get(14),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(14),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(14),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | "+ (getSlot(slots,input.getPeriodTimes().get(15),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(15),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(15),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | "+ (getSlot(slots,input.getPeriodTimes().get(16),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(16),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(16),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | "+ (getSlot(slots,input.getPeriodTimes().get(17),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(17),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(17),currGroup).getSubject().getType()) : String.format("%1$21s","----------------"))+ " |");
            System.out.println("        | " + (getSlot(slots,input.getPeriodTimes().get(12),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(12),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(12),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | " + (getSlot(slots,input.getPeriodTimes().get(13),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(13),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(13),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | "+ (getSlot(slots,input.getPeriodTimes().get(14),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(14),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(14),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | "+ (getSlot(slots,input.getPeriodTimes().get(15),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(15),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(15),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | "+ (getSlot(slots,input.getPeriodTimes().get(16),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(16),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(16),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | "+ (getSlot(slots,input.getPeriodTimes().get(17),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(17),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(17),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------"))+ " |");
            System.out.println("--------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+");
            System.out.println("TH      | " + (getSlot(slots,input.getPeriodTimes().get(18),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(18),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(18),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | " + (getSlot(slots,input.getPeriodTimes().get(19),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(19),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(19),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | "+ (getSlot(slots,input.getPeriodTimes().get(20),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(20),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(20),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | "+ (getSlot(slots,input.getPeriodTimes().get(21),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(21),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(21),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | "+ (getSlot(slots,input.getPeriodTimes().get(22),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(22),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(22),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | "+ (getSlot(slots,input.getPeriodTimes().get(23),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(23),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(23),currGroup).getSubject().getType()) : String.format("%1$21s","----------------"))+ " |");
            System.out.println("        | " + (getSlot(slots,input.getPeriodTimes().get(18),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(18),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(18),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | " + (getSlot(slots,input.getPeriodTimes().get(19),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(19),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(19),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | "+ (getSlot(slots,input.getPeriodTimes().get(20),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(20),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(20),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | "+ (getSlot(slots,input.getPeriodTimes().get(21),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(21),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(21),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | "+ (getSlot(slots,input.getPeriodTimes().get(22),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(22),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(22),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | "+ (getSlot(slots,input.getPeriodTimes().get(23),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(23),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(23),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------"))+ " |");
            System.out.println("--------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+");
            System.out.println("FR      | " + (getSlot(slots,input.getPeriodTimes().get(24),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(24),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(24),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | " + (getSlot(slots,input.getPeriodTimes().get(25),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(25),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(25),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | "+ (getSlot(slots,input.getPeriodTimes().get(26),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(26),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(26),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | "+ (getSlot(slots,input.getPeriodTimes().get(27),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(27),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(27),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | "+ (getSlot(slots,input.getPeriodTimes().get(28),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(28),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(28),currGroup).getSubject().getType()) : String.format("%1$21s","----------------")) +" | "+ (getSlot(slots,input.getPeriodTimes().get(29),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(29),currGroup).getSubject().getName() +", " + getSlot(slots,input.getPeriodTimes().get(29),currGroup).getSubject().getType()) : String.format("%1$21s","----------------"))+ " |");
            System.out.println("        | " + (getSlot(slots,input.getPeriodTimes().get(24),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(24),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(24),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | " + (getSlot(slots,input.getPeriodTimes().get(25),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(25),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(25),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | "+ (getSlot(slots,input.getPeriodTimes().get(26),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(26),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(26),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | "+ (getSlot(slots,input.getPeriodTimes().get(27),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(27),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(27),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | "+ (getSlot(slots,input.getPeriodTimes().get(28),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(28),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(28),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------")) + " | "+ (getSlot(slots,input.getPeriodTimes().get(29),currGroup) != null ? String.format("%1$21s",getSlot(slots,input.getPeriodTimes().get(29),currGroup).getTeacher().getName()+", " + getSlot(slots,input.getPeriodTimes().get(29),currGroup).getRoom().getNumber()) : String.format("%1$21s","----------------"))+ " |");

            System.out.println("---------------------------------------------------------------------------------------------------------------------------------------------------------");
        }
    }

    private static Slot getSlot(List<Slot> slots, PeriodTime time, StudentGroup group){
        for(int i = 0; i < slots.size(); i++){
            if(slots.get(i).getGroup() == group &&  slots.get(i).getPeriodTime() == time){
                return slots.get(i);
            }
        }
        return null;
    }
}
